  nodered:
    container_name: nodered
    build: .//services/nodered/.
    restart: unless-stopped
    user: "0"
    privileged: true
    ports:
      - "1880:1880"
    volumes:
      - .//volumes/nodered/data:/data
